jobs:
  - name: generate-test-data-dev
    max_in_flight: 1
    plan:
      - in_parallel:
         - get: dataworks-behavioural-framework
           trigger: false
         - put: meta
           resource: meta-development
      - .: (( inject meta.plan.generate-test-data ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
