jobs:
  - name: start-cluster-development
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
            START_DT: "2021-04-12"
            END_DT: "2021-04-12"
            CLEAN_UP_FLG: "False"
            E2E_TEST_FLG: "False"

  - name: start-cluster-qa
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            START_DT: "2021-03-24"
            END_DT: "2021-03-24"
            CLEAN_UP_FLG: "False"
            E2E_TEST_FLG: "False"

  - name: start-cluster-integration
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            START_DT: "2021-03-24"
            END_DT: "2021-03-24"
            CLEAN_UP_FLG: "False"
            E2E_TEST_FLG: "False"

  - name: start-cluster-preprod
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            START_DT: "2021-03-24"
            END_DT: "2021-03-24"
            CLEAN_UP_FLG: "False"
            E2E_TEST_FLG: "False"

  - name: start-cluster-production
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            START_DT: "2021-03-24"
            END_DT: "2021-03-24"
            CLEAN_UP_FLG: "False"
            E2E_TEST_FLG: "False"
