jobs:
  - name: start-cluster-development
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
            CORRELATION_ID: "kickstart_vacancy_analytical_dataset_generation"
            JOB_NAME: "kickstart"
            MODULE_NAME: "vacancy"
            LAST_PROCESS_DT: "2021-01-24"

  - name: start-cluster-qa
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            CORRELATION_ID: "kickstart_vacancy_analytical_dataset_generation"
            JOB_NAME: "kickstart"
            MODULE_NAME: "vacancy"
            LAST_PROCESS_DT: "2021-01-19"

  - name: start-cluster-integration
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            CORRELATION_ID: "kickstart_vacancy_analytical_dataset_generation"
            JOB_NAME: "kickstart"
            MODULE_NAME: "vacancy"
            LAST_PROCESS_DT: "2021-01-19"

  - name: start-cluster-preprod
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            CORRELATION_ID: "kickstart_vacancy_analytical_dataset_generation"
            JOB_NAME: "kickstart"
            MODULE_NAME: "vacancy"
            LAST_PROCESS_DT: "2021-01-19"

  - name: start-cluster-production
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            CORRELATION_ID: "kickstart_vacancy_analytical_dataset_generation"
            JOB_NAME: "kickstart"
            MODULE_NAME: "vacancy"
            LAST_PROCESS_DT: "2020-01-19"
