jobs:
  - name: stop-cluster-development
    plan:
      - .: (( inject meta.plan.stop-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci

  - name: stop-cluster-qa
    plan:
      - .: (( inject meta.plan.stop-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci

  - name: stop-cluster-integration
    plan:
      - .: (( inject meta.plan.stop-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: stop-cluster-preprod
    plan:
      - .: (( inject meta.plan.stop-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci

  - name: stop-cluster-production
    plan:
      - .: (( inject meta.plan.stop-cluster ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
